### ISSUE TITLE
gizmo is not rendering when use EffectComposer render pipeline

### ISSUE THREAD

**Issue by augusttty** [Fennec-hub/three-viewport-gizmo#1]

**Comment by Fennec-hub** [comment]
Fixed! thanks for the heads up.

https://fennec-hub.github.io/three-viewport-gizmo/#/composer.

**Comment by augusttty** [comment]
After upgraded ,checked your demo code and execute the `gzimo.render()` **after** scene's render and finally it works, thanks.
