### ISSUE TITLE
Gizmo not correctly resizing

### ISSUE THREAD

**Issue by dirkk0** [Fennec-hub/three-viewport-gizmo#11]
Hi,
thanks for the Gizmo project, it's working great for me! - with two exceptions, though.

I created an example where threejs is embedded in a webcomponent, and two problems arise:
a) when you put the gizmo render *before* the renderer (as it is in the documentation), nothing ist displayed. I think this is also the problem with #9 .
b) the gizmo resize breaks the renderer resize, resulting in a distorted cube. This is a real showstopper for me.

Regarding b), I see there is a pull request waiting here: #10 Maybe this is related?

Here is the example:
https://glitch.com/edit/#!/threejs-webcomponent-viewportgizmo-1

Thanks for looking into this!
Cheers, Dirk

**Comment by Fennec-hub** [comment]
Fix [#13](https://github.com/Fennec-hub/three-viewport-gizmo/issues/13)
