### ISSUE TITLE
Rendering of gizmo not in correct place if canvas is not left aligned

### ISSUE THREAD

**Issue by CustomBrandCo** [Fennec-hub/three-viewport-gizmo#12]
I have a scene which I am restricting to an aspect ratio of 1920x1080 and centring the canvas. The canvas is being added to the div with id of '3dContainer' as shown below.

`<div style="display: flex; justify-content: center; align-items: center"><div id="3dContainer" style="border: 1px solid black; position: relative" ></div></div>`

I am passing the div '3dContainer' to the gizmo via options like this:

`const container = document.getElementById('3dContainer');const options = {container: container,placement: "top-right"`

But when I view the web page, the gizmo can render off the canvas when the page is too wide as shown in the image below.

The div for the gizmo and controls are in the correct place, just the rendering that isn't.

I'm guessing that you're using the x value of the control div bounds for placing the rendering but are not offsetting the x value for the canvas bounds?

![Screenshot 2024-09-25 152815](https://github.com/user-attachments/assets/9b026906-8407-42de-b4eb-58109be6d445)

**Comment by Fennec-hub** [comment]
Fix [#13](https://github.com/Fennec-hub/three-viewport-gizmo/issues/13)
