### ISSUE TITLE
Add maintainers to the project

### ISSUE THREAD

**Issue by DraTeots** [Fennec-hub/three-viewport-gizmo#13]
Dear developer. It is a good project. And people contribute to it by writing issues and making PRs. There is no response to that for months now. Which is OK, it is an open source project, everybody could get busy, ill, real life, whatever. But it is pity that community is trying to contribute but PRs got stuck. Would you mind adding people, who making the PRs to project developers/maintainers, if you don't have time for it.

**Comment by Fennec-hub** [comment]
Dear contributor,

First off, I want to express my sincere apologies for the lack of response over the past few months. I don’t want to sound pitiful, but unfortunately, I was sick and unable to concentrate on maintaining the project as much as I’d have liked.

I’ve recently managed to review the entire repository and went through most of the issues, addressing several of them. Additionally, I’ve updated the documentation, so please check out the latest version—it should provide much better guidance on using and contributing to the project.

I’m open to adding maintainers to help keep things running smoothly. If anyone with the right skills is interested in taking on a more active role, please reach out—I’d be glad to consider it.

Again, I’m truly sorry it’s come to this point, and I really appreciate your patience and consideration.

Thank you for your support and contributions.
