### ISSUE TITLE
Unexpected Behavior When Using with Other Controls

### ISSUE THREAD

**Issue by Error806** [Fennec-hub/three-viewport-gizmo#14]
When using viewportGizmo with other controls, unexpected behavior occurs.

For example, this is a screen recording video in [OrbitControls](https://fennec-hub.github.io/three-viewport-gizmo/#/orbit) in Examples, by rotating the viewport, the positive y-axis of the scene can point downward,  this is not possible in either Three.js or when using viewportGizmo alone.:

https://github.com/user-attachments/assets/f4d86832-dfe4-4087-8942-8db146a50941

In contrast, here's a screen recording from the [Standalone](https://fennec-hub.github.io/three-viewport-gizmo/) in Examples, where it's impossible to make the scene's Y-axis point downward:

https://github.com/user-attachments/assets/ae36940e-7b97-4b56-b8e9-10e24787b276

I suspect the issue arises because, during dragging, the viewportGizmo's rotation (an Euler angle) is modified by adjusting the X and Y components. To ensure this process works correctly, the Z component of the rotation should remain at 0, which is maintained when using viewportGizmo alone.
Here is the current code, in [ViewportGizmo](https://github.com/Fennec-hub/three-viewport-gizmo/blob/main/lib/ViewportGizmo.ts)
```typescript
mouseAngle
  .set(e.clientX, e.clientY)
  .sub(mouseStart)
  .multiplyScalar((1 / this._domRect.width) * Math.PI);

this.rotation.x = clamp(
  rotationStart.x + mouseAngle.y,
  Math.PI / -2 + 0.001,
  Math.PI / 2 - 0.001
);
this.rotation.y = rotationStart.y + mouseAngle.x; 
this.updateMatrixWorld();
```

However, when used with other controls, the viewportGizmo's update method is called. This method sets the viewportGizmo's quaternion to the inverse of the camera's quaternion, which also alters the viewportGizmo's rotation. In Three.js, when converting quaternions to Euler angles, certain conditions can result in a non-zero Z-axis rotation component. This discrepancy leads to unexpected behavior during rotation calculations while dragging.

For example, calculating an Euler angle in Three.js under these conditions results in a Z-axis rotation component:
![three截图](https://github.com/user-attachments/assets/6e3bc359-33d0-48dd-aeb5-8d979bf42780)

**Comment by Fennec-hub** [comment]
Using `Quaternion` instead of `Euler` rotation is the way to go, I'm also working on the relative position issue.

Appreciate the feedback, I'll notify you once the next version is ready.

**Comment by Fennec-hub** [comment]
This was one of the hardest issue to fix, I tried with quaternions and it only got worst! I had to compute the rotation angle with spherical coordinates, and now it's working like a charm!

https://github.com/Fennec-hub/three-viewport-gizmo/blob/291992c3a03648acf9ac7318a9c38ad7e4c797d6/lib/ViewportGizmo.ts#L528C2-L593C4
