### ISSUE TITLE
Square artifacts around circles

### ISSUE THREAD

**Issue by crystalfp** [Fennec-hub/three-viewport-gizmo#18]
Sorry for being so annoying today.
As you see in the images below (first on Windows, second on Linux) the circles are slightly cut like there is an off-by-one error in the size of the base square, I think.
![image](https://github.com/user-attachments/assets/1bb05b43-daa4-4bdf-bb76-03981825bae4)
![image](https://github.com/user-attachments/assets/39ad776a-eef5-428e-8081-59225f52887e)
Here are the options I use:
```
        size: 150,
        placement: "bottom-right",
        lineWidth: 30,
        resolution: 64,
        background: {enabled: true, color: "#FFFFFF", opacity: 0, hover: {color: "#FFFFFF", opacity: .2}},
        x: {color: "#FF0000", labelColor: "#000", label: "X"},
        y: {color: "#79FF00", labelColor: "#000", label: "Y"},
        z: {color: "#0000FF", labelColor: "#000", label: "Z"},
        nx: {scale: 0},
        ny: {scale: 0},
        nz: {scale: 0},
```
Thanks for looking!

**Comment by Fennec-hub** [comment]
I see exactly what you mean... Should be an easy fix.

![image](https://github.com/user-attachments/assets/fbdbc985-a15e-44da-92ec-396489003293)

You're not annoying at all. In fact, I'm caught up in tunnel vision with other issues, and having an outside perspective is really helpful.

**Comment by Fennec-hub** [comment]
I've double checked the math, and everything seems OK! 

Tuns out to be a texture `resolution` issue, 

![image](https://github.com/user-attachments/assets/93cdcadb-2166-4945-a244-379f4d8b83aa)

If you set the `resolution` option to a higher value, the square artifacts disappear.

And thanks again for the valuable review.
