### ISSUE TITLE
integration with `<model-viewer>`

### ISSUE THREAD

**Issue by elalish** [Fennec-hub/three-viewport-gizmo#2]
This gizmo looks great and I know of a number of editors based on `<model-viewer>` that could use it (I would personally add it to two: https://modelviewer.dev/editor/ and https://manifoldcad.org/). However, though `<model-viewer>` is built on Three.js, it doesn't expose Three's internals - you can't access the renderer or the camera.

`<model-viewer>`'s camera already does smooth interpolation by default, so all I really need is click events I can use to set the theta and phi of the camera. Unless you're interested in making a version of your gizmo that takes a `<model-viewer>` element as input, which would be amazing!

**Comment by Fennec-hub** [comment]
Just like you pointed out the the rendered is not exposed. I don't have mush experience with web components, but from my understanding, you'll probably need to create a new `addon`, same as `<model-viewer-effects>`, see the way it's implemented here:

https://github.com/google/model-viewer/blob/master/packages/model-viewer-effects/src/effect-composer.ts

Can't promise anything, but i'll give it a try on my free time.
