### ISSUE TITLE
I want to adjust the z-index.

### ISSUE THREAD

**Issue by ma2yama** [Fennec-hub/three-viewport-gizmo#21]
Currently, the z-Index is set to 1000, but I'm having trouble with the viewportGizmo being above the other elements.
I'd like to be able to adjust the z-Index with option, or edit the DOM.

**Comment by Fennec-hub** [comment]
You can set the `className` or `id` options, and than set the gizmo css as you wish (you'll need to add `!important` for each property to override the original style)

Checkout the [Responsive example](https://fennec-hub.github.io/three-viewport-gizmo/examples/responsive.html?type=sphere).
