### ISSUE TITLE
Wrong constructor, container undefined

### ISSUE THREAD

**Issue by doczoidberg** [Fennec-hub/three-viewport-gizmo#4]
I try to get it run within my angular application. In afterviewinit (DOM element exists):

        const viewportGizmoElement = document.getElementById('viewportGizmo') as any;
        this.viewportGizmo = new ViewportGizmo(this.renderer, this.camera, container);

but on construction i get:

Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'offsetHeight')
TypeError: Cannot read properties of undefined (reading 'offsetHeight')
    at Et.update (three-viewport-gizmo.js:279:1)

**Comment by Fennec-hub** [comment]
There was an error on the README page; it should actually be:

```javascript
this.viewportGizmo = new ViewportGizmo(this.camera, this.renderer, container);
```

I've updated the library but somehow forgot about the examples in the README page.

You can live test it here: https://jsfiddle.net/eovL86hy/1/

My apologies for the confusion.

**Comment by doczoidberg** [comment]
thanks for your answer, but already changed the constructor parameters. everything works but the rendering is invisible. unfortunately i can't reproduce with that fiddle

**Comment by doczoidberg** [comment]
hmm i don't use setAnimationLoop.

https://jsfiddle.net/yg78x5na/

so i need it?

**Comment by Fennec-hub** [comment]
Hi,

I've looked into it and added a new demo with a static renderer. 

[Demo](https://fennec-hub.github.io/three-viewport-gizmo/#/static) - [Source](https://github.com/Fennec-hub/three-viewport-gizmo/blob/main/demo/src/static.ts).

There was also a problem with the "change" event, which has been fixed. So, you'll need to reinstall the package with the new version "0.1.4". (You may also need to clear the npm cache.)

Please give it a try, and let me know your feedback.

**Comment by Fennec-hub** [comment]
I'm suspecting one last thing, updated to version "0.1.5". please reinstall and try again.

I've also put together a new jsfiddle, with the new version and a static renderer. here is the [live demo ](https://jsfiddle.net/hy5971j2/5/). Use it with your code, I'll look into it.

**Comment by doczoidberg** [comment]
thanks, but also didn't helped. I try to make a minimal example with angular.

**Comment by Fennec-hub** [comment]
I'll close this at the moment. Feel free to reopen and share the example.

**Comment by doczoidberg** [comment]
thanks. i use a weird splitter container and hacked your sources to fit your great gizmo component into my app
