### ISSUE TITLE
nothing rendered. dom element and scene created

### ISSUE THREAD

**Issue by doczoidberg** [Fennec-hub/three-viewport-gizmo#5]
Hi,

i use three.js 0.162.0 within an angular project and added everything as described.
what can i do when nothing of the gizmo is renderered? DOM is created inside the container but nothing is rendered on it.

        const viewportGizmoElement = document.getElementById('viewportGizmo') as any;
        var options = {
          container: viewportGizmoElement,
          size: 100,
        }
        this.viewportGizmo = new ViewportGizmo(this.camera, this.renderer, options);
        this.viewportGizmo.target = this.controls.target;

handles work and camera moves when clicking the invisible axes.

**Comment by Fennec-hub** [comment]
Can you please reproduce the issue here:  https://jsfiddle.net/eovL86hy/1/

Sorry for the delay!

**Comment by BartaG512** [comment]
Hello! I've recreated the issue 
Please check: https://stackblitz.com/edit/stackblitz-starters-4kcphs?file=src%2Fapp%2Fapp.component.ts,index.js,src%2Fapp%2Fapp.component.html

**Comment by meszaros-lajos-gyorgy** [comment]
It's also not showing me anything, I'm using threejs 0.171.0: https://github.com/arx-tools/editor/blob/52cf20550d0ce5b35474f108e2e1639daeb2b8eb/src/index.ts

**Comment by Fennec-hub** [comment]
Sorry for the delay, 

This line should fix the issue as long as the canvas fits the entire element
`container: canvas.parentElement as HTMLElement`
